image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip

stages:
  - test
  - pages

before_script:
  - python3 -V  # Print out python version for debugging
  - git clone --depth=1 https://github.com/gem/oq-engine.git 
  - pip install -r oq-engine/requirements-py36-linux64.txt
  - pip install -e oq-engine
  - pip install -r requirements.txt
  - pip install -e .


test:
  stage: test
  script:
    - python3 -m unittest discover

pages:
  stage: pages
  script:
    - pip install sphinx
    - cd docs ; sphinx-apidoc -o source/ ../hz_test ; make html
    - mv build/html/ ../public/

  artifacts:
    paths:
    - public
  only:
    - docs