image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
#
#test:
#  script:
#    - python 

install:
  script:
    - git clone --depth=1 https://github.com/gem/oq-engine.git 
    - pip -q install -r oq-engine/requirements-py37-linux64.txt -r oq-engine/requirements-extra-py37-linux64.txt
    - pip -q install -e oq-engine
    - pip install geopandas
    - pip install rtree
    - pip install -r requirements.txt
    - pip install -e .

pages:
  script:
    - pip install sphinx
    - cd docs ; sphinx-apidoc -o source/ ../hz_test ; make html
    - mv build/html/ ../public/

  artifacts:
    paths:
    - public
  only:
    - docs