image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip

stages:
  - pages
  - test

before_script:
  - ls
  - python3 -V  # Print out python version for debugging
  - git clone --depth=1 https://github.com/gem/oq-engine.git 
  - pip install -r oq-engine/requirements-py36-linux64.txt
  - pip install -e oq-engine
  - pip install -r requirements.txt
  - pip install -e .


test:
  stage: test
  script:
    # fix matplotlib backend error
    - touch ~/.config/matplotlib/matplotlibrc
    - echo "backend: svg" > ~/.config/matplotlib/matplotlibrc
    - pip install pytest
    - py.test hztest tests -W ignore::UserWarning

pages:
  stage: pages
  script:
    - pip install sphinx
    - pip install recommonmark
    - cd docs ; sphinx-apidoc -o source/ ../hztest ; make html
    - mv build/html/ ../public/

  artifacts:
    paths:
    - public
  only:
    - master