image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
#
#test:
#  script:
#    - python 



pages:
  script:
    - pip install sphinx
    - cd docs ; make html
    - mv build/html/ ../public

  artifacts:
    paths:
    - public
  only:
    - docs