sudo: true

language: python

cache: pip

python: 
  - "3.7"

install:
  - cat /etc/*-release
  - sudo apt-get update
  - sudo apt-get -y install libspatialindex-dev
  - python3 -V # Print out python version for debugging
  - git clone --depth=1 https://github.com/gem/oq-engine.git
  - pip install -r oq-engine/requirements-py37-linux64.txt
  - pip install -e oq-engine
  - pip install --no-cache-dir https://gitlab.com/cossatot/wheelz/raw/master/h3-py/h3-3.4.3-cp37-cp37m-linux_x86_64.whl
  - pip install -r requirements.txt
  - pip install -e .

jobs:
  include:

    - stage: test
      script:
        - pip install pytest
        - py.test openquake tests -W ignore::UserWarning
      deploy:

    - stage: pages
      script:
        - pip install sphinx
        - pip install recommonmark
        - cd doc_src ; sphinx-apidoc -o source/ ../openquake/ ; make html
        - touch build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch:
      - master
      - docs
  local_dir: build/html/