"""
Functionality for writing reports demonstrating the results of the Hamlet
testing.
"""

import os
from typing import Optional

import numpy as np
import matplotlib.pyplot as plt
from geopandas import GeoDataFrame
from jinja2 import Environment, FileSystemLoader

from openquake.hme.utils.plots import plot_likelihood_map

BASE_DATA_PATH = os.path.dirname(__file__)
template_dir = os.path.join(BASE_DATA_PATH, 'templates')


def _init_env() -> Environment:
    file_loader = FileSystemLoader(template_dir)
    env = Environment(loader=file_loader)
    return env


def generate_basic_report(cfg: dict,
                          results: dict,
                          bin_gdf: Optional[GeoDataFrame] = None,
                          eq_gdf: Optional[GeoDataFrame] = None) -> None:
    """
    Generates an HTML report with the results of the various evaluations or
    tests performed by Hamlet.

    :param cfg:
        Configuration from parsed yaml file.

    :type cfg:
        `dict`

    :param results:
        Results of the model evaluations. Should be auto-generated by Hamlet.

    :type results:
        `dict`

    :param bin_gdf:
        All of the :class:`~openquake.hme.utils.bins.SpacemagBin` s used in the
        evaluations.

    :type bin_gdf:
        `geopandas.GeoDataFrame`

    :param eq_gdf:
        Observed earthquakes used in the evaluations.

    :type eq_gdf:
        `geopandas.GeoDataFrame`

    """

    env = _init_env()
    report_template = env.get_template('basic_report.html')

    render_result_text(env=env,
                       cfg=cfg,
                       results=results,
                       bin_gdf=bin_gdf,
                       eq_gdf=eq_gdf)

    report = report_template.render(cfg=cfg, results=results)

    with open(cfg['report']['basic']['outfile'], 'w') as report_file:
        report_file.write(report)


def render_result_text(env: Environment,
                       cfg: dict,
                       results: dict,
                       bin_gdf: Optional[GeoDataFrame] = None,
                       eq_gdf: Optional[GeoDataFrame] = None) -> None:

    if 'gem' in results.keys():
        if 'model_mfd' in results['gem'].keys():
            render_mfd(env=env, cfg=cfg, results=results)

        if 'likelihood' in results['gem'].keys():
            render_likelihood(env=env,
                              cfg=cfg,
                              results=results,
                              bin_gdf=bin_gdf,
                              eq_gdf=eq_gdf)

        if 'max_mag_check' in results['gem'].keys():
            render_max_mag(env=env, cfg=cfg, results=results)

    if 'relm' in results.keys():
        if 'N_test' in results['relm'].keys():
            render_N_test(env=env, cfg=cfg, results=results)

    if 'sanity' in results.keys():
        raise NotImplementedError("Reporting for sanity not implemented.")


def render_mfd(env: Environment, cfg: dict, results: dict):
    mfd_template = env.get_template('mfd.html')
    results['gem']['model_mfd']['rendered_text'] = mfd_template.render(
        cfg=cfg, results=results)


def render_likelihood(env: Environment,
                      cfg: dict,
                      results: dict,
                      bin_gdf: GeoDataFrame,
                      eq_gdf: Optional[GeoDataFrame] = None) -> None:

    total_log_like = np.sum(bin_gdf['log_like']) / bin_gdf.shape[0]
    total_log_like = "{0:2f}".format(total_log_like)

    if 'plot_eqs' in cfg['report']['basic'].keys():
        plot_eqs = cfg['report']['basic']['plot_eqs']
    else:
        plot_eqs = False

    if 'map_epsg' in cfg['report']['basic'].keys():
        map_epsg = cfg['report']['basic']['map_epsg']
    else:
        map_epsg = None

    likelihood_map_str = plot_likelihood_map(bin_gdf,
                                             plot_eqs=plot_eqs,
                                             eq_gdf=eq_gdf,
                                             map_epsg=map_epsg)

    likelihood_template = env.get_template('likelihood.html')

    results['gem']['likelihood']['rendered_text'] = likelihood_template.render(
        cfg=cfg,
        results=results,
        total_log_like=total_log_like,
        likelihood_map_str=likelihood_map_str)


def render_max_mag(env: Environment, cfg: dict, results: dict) -> None:

    if results['gem']['max_mag_check']['val'] == []:
        max_mag_results = (
            'PASS: All bins produce seismicity greater than observed.')
    else:
        max_mag_results = (
            "Bins {} have higher observed seismicity than they can produce.".
            format(results['gem']['max_mag_check']['val']))

    max_mag_template = env.get_template('max_mag_check.html')
    results['gem']['max_mag_check']['rendered_text'] = max_mag_template.render(
        max_mag_results=max_mag_results)


def render_N_test(env: Environment, cfg: dict, results: dict) -> None:
    n_test = env.get_template('n_test.html')
    results['relm']['N_test']['rendered_text'] = n_test.render(
        res=results['relm']['N_test']['val'])